### ISSUE TITLE
国服 IC-1 结算页面截图无法被识别

### ISSUE THREAD

**Issue by Tinhone** [penguin-statistics/recognizer#17]
反馈截图识别缺陷弹窗中，识别结果一栏为空

浏览器：Firefox V88.0

错误提示：
```
非结算页面截图或内部错误
若这确实是一张结算页面截图，请检查您是否选择了正确的服务器
Result::False
```

浏览器控制台全部日志，错误日志展示详细信息，敏感信息隐去：
```
08:05:23.867 由于不符合规范，Cookie “_ga_4VJR7KRK8D”在未来会被视为“https://penguin-stats.cn/report/recognition”的跨网站 Cookie。 2 recognition
08:05:23.978 由于不符合规范，Cookie “_ga_4VJR7KRK8D”在未来会被视为“https://penguin-stats.cn/css/app.654d8e6e.css”的跨网站 Cookie。 app.654d8e6e.css
08:05:23.989 由于不符合规范，Cookie “_ga_4VJR7KRK8D”在未来会被视为“https://penguin-stats.cn/css/chunk-vendors.9b89affe.css”的跨网站 Cookie。 chunk-vendors.9b89affe.css
08:05:24.000 由于不符合规范，Cookie “_ga_4VJR7KRK8D”在未来会被视为“https://penguin-stats.cn/js/app.e6f3f7df.js”的跨网站 Cookie。 app.e6f3f7df.js
08:05:24.013 由于不符合规范，Cookie “_ga_4VJR7KRK8D”在未来会被视为“https://penguin-stats.cn/js/chunk-vendors.e6bcee3d.js”的跨网站 Cookie。 chunk-vendors.e6bcee3d.js
08:05:24.058 failed to render preloader TypeError: o is undefined
    r https://penguin-stats.cn/report/recognition:1
    render https://penguin-stats.cn/report/recognition:1
    e https://penguin-stats.cn/report/recognition:1
    vQE2 https://penguin-stats.cn/report/recognition:1
    vQE2 https://penguin-stats.cn/report/recognition:1
    c https://penguin-stats.cn/report/recognition:1
    parcelRequire https://penguin-stats.cn/report/recognition:1
    <anonymous> https://penguin-stats.cn/report/recognition:1
recognition:1:7904
08:05:24.429 route changed / instrument.js:109:42
08:05:24.430 (info) [RandomizedLogo] randomizing logo instrument.js:109:42
08:05:24.435 (info) [Build] Hello from Penguin Statistics! :D Running platform 'web' with 'production' instrument.js:109:42
08:05:24.437 (info) [Theme] setting to light instrument.js:109:42
08:05:24.443 (info) [ThemeStyle] detecting theme style... instrument.js:109:42
08:05:24.446 (info) [i18n] locale: zh | saving to vuex: false instrument.js:109:42
08:05:24.864 (log) [ServiceWorker] successfully replaced to a no-op SW 
ServiceWorkerRegistration { installing: null, waiting: null, active: ServiceWorker, scope: "https://penguin-stats.cn/", updateViaCache: "imports", onupdatefound: null, pushManager: PushManager }
instrument.js:109:42
08:05:24.878 Will-change 的内存消耗过高。限额是文档的表面区域乘以 3（837828 像素），will-change 超出限额的部分将被忽略。 recognition
08:05:24.943 由于不符合规范，Cookie “_ga_4VJR7KRK8D”在未来会被视为“https://penguin-stats.cn/fonts/roboto-400.1ad82d93.woff2”的跨网站 Cookie。 roboto-400.1ad82d93.woff2
08:05:25.087 由于不符合规范，Cookie “_ga_4VJR7KRK8D”在未来会被视为“https://penguin-stats.cn/css/recognition.dd1f7533.css”的跨网站 Cookie。 recognition.dd1f7533.css
08:05:25.088 由于不符合规范，Cookie “_ga_4VJR7KRK8D”在未来会被视为“https://penguin-stats.cn/css/font-noto-serif-sc.1df1d92d.css”的跨网站 Cookie。 font-noto-serif-sc.1df1d92d.css
08:05:25.096 由于不符合规范，Cookie “_ga_4VJR7KRK8D”在未来会被视为“https://penguin-stats.cn/js/recognition.bc48b4b7.js”的跨网站 Cookie。 recognition.bc48b4b7.js
08:05:25.097 由于不符合规范，Cookie “_ga_4VJR7KRK8D”在未来会被视为“https://penguin-stats.cn/js/chunk-2d0c8407.1118d563.js”的跨网站 Cookie。 chunk-2d0c8407.1118d563.js
08:05:25.100 由于不符合规范，Cookie “_ga_4VJR7KRK8D”在未来会被视为“https://penguin-stats.cn/js/chunk-2d208e4e.3dcdb6f4.js”的跨网站 Cookie。 chunk-2d208e4e.3dcdb6f4.js
08:05:25.101 由于不符合规范，Cookie “_ga_4VJR7KRK8D”在未来会被视为“https://penguin-stats.cn/js/font-noto-serif-sc.efe0a912.js”的跨网站 Cookie。 font-noto-serif-sc.efe0a912.js
08:05:25.105 由于不符合规范，Cookie “_ga_4VJR7KRK8D”在未来会被视为“https://penguin-stats.cn/js/chunk-2d212be3.f419e7be.js”的跨网站 Cookie。 chunk-2d212be3.f419e7be.js
08:05:25.118 由于不符合规范，Cookie “_ga_4VJR7KRK8D”在未来会被视为“https://penguin-stats.cn/PenguinStats/api/v2/_private/result/trend/CN”的跨网站 Cookie。 CN
08:05:25.131 由于不符合规范，Cookie “_ga_4VJR7KRK8D”在未来会被视为“https://penguin-stats.cn/fonts/roboto-700.0e6d7275.woff2”的跨网站 Cookie。 roboto-700.0e6d7275.woff2
08:05:25.132 由于不符合规范，Cookie “_ga_4VJR7KRK8D”在未来会被视为“https://penguin-stats.cn/fonts/roboto-500.5b4de98d.woff2”的跨网站 Cookie。 roboto-500.5b4de98d.woff2
08:05:25.138 由于不符合规范，Cookie “_ga_4VJR7KRK8D”在未来会被视为“https://penguin-stats.cn/fonts/materialdesignicons-webfont.d0066537.woff2”的跨网站 Cookie。 materialdesignicons-webfont.d0066537.woff2
08:05:25.210 route changed /report/recognition instrument.js:109:42
08:05:25.210 (info) [RandomizedLogo] randomizing logo instrument.js:109:42
08:05:25.627 (info) [ObjectManager] fetched data "trends" at 1693872325627 for server "CN" instrument.js:109:42
08:05:25.707 (log) [RandomBackground] created blob:https://penguin-stats.cn/049bfb19-e887-4882-b3dc-2730958f216a | (skipping revoke) instrument.js:109:42
08:05:25.708 (log) [RandomBackground] created blob:https://penguin-stats.cn/0fcc82d9-e3f2-4be8-91c7-9fa4984d9acd | revoking blob:https://penguin-stats.cn/049bfb19-e887-4882-b3dc-2730958f216a instrument.js:109:42
08:05:25.751 (info) [Capacitor:App] App state changed with new state 
Object { isActive: true }
instrument.js:109:42
08:05:26.178 (info) [Capacitor:App] App state changed with new state 
Object { isActive: false }
instrument.js:109:42
08:05:26.592 (info) [Capacitor:App] App state changed with new state 
Object { isActive: true }
instrument.js:109:42
08:05:27.142 由于不符合规范，Cookie “_ga_4VJR7KRK8D”在未来会被视为“https://penguin-stats.cn/PenguinStats/api/v2/stats?server=CN”的跨网站 Cookie。 stats
08:05:27.273 (info) [ObjectManager] fetched data "stats" at 1693872327274 for server "CN" instrument.js:109:42
08:05:28.386
某些 Cookie 滥用推荐的“SameSite“属性 3
08:05:28.548 (info) [i18n] fetched language: zh mappedLang: zh_CN instrument.js:109:42
08:05:28.851 由于不符合规范，Cookie “_ga_4VJR7KRK8D”在未来会被视为“https://penguin-stats.cn/favicon/apple-touch-icon.png”的跨网站 Cookie。 apple-touch-icon.png
08:05:28.949 由于不符合规范，Cookie “_ga_4VJR7KRK8D”在未来会被视为“https://penguin-stats.cn/favicon/favicon-32x32.png”的跨网站 Cookie。 favicon-32x32.png
08:05:28.973 (info) [MirrorSelector] successfully retrived geoip info 
Object { *** }
instrument.js:109:42
08:05:28.973 (info) [MirrorSelector] current mirror: cn | popup? false instrument.js:109:42
08:05:29.056 (info) [CrispCustomizer] triggered | chat:loaded instrument.js:109:42
08:05:31.586 已拦截跨源请求：同源策略禁止读取位于 ‘https://www.google-analytics.com/j/collect?v=1&_v=j101&a=736899179&t=event&_s=1&dl=https%3A%2F%2Fpenguin-stats.cn%2Freport%2Frecognition&ul=zh-cn&de=UTF-8&dt=%E6%88%AA%E5%9B%BE%E8%AF%86%E5%88%AB%20%E2%80%B9%20%E6%8E%89%E8%90%BD%E6%B1%87%E6%8A%A5%20%E2%94%82%20%E4%BC%81%E9%B9%85%E7%89%A9%E6%B5%81%E6%95%B0%E6%8D%AE%E7%BB%9F%E8%AE%A1&sd=24-bit&sr=1536x864&vp=1536x802&je=0&ec=runtime&ea=version&el=v3.13.7&_u=CACAAEABEAAAACAAI~&jid=1411315286&gjid=1109798084&cid=426329494.1686413173&tid=UA-142226262-4&_gid=739023401.1693838405&_r=1&_slc=1&z=1778715342’ 的远程资源。（原因：凭据不支持，如果 CORS 头 ‘Access-Control-Allow-Origin’ 为 ‘*’）。

08:05:31.587 已拦截跨源请求：同源策略禁止读取位于 https://www.google-analytics.com/j/collect?v=1&_v=j101&a=736899179&t=event&_s=1&dl=https%3A%2F%2Fpenguin-stats.cn%2Freport%2Frecognition&ul=zh-cn&de=UTF-8&dt=%E6%88%AA%E5%9B%BE%E8%AF%86%E5%88%AB%20%E2%80%B9%20%E6%8E%89%E8%90%BD%E6%B1%87%E6%8A%A5%20%E2%94%82%20%E4%BC%81%E9%B9%85%E7%89%A9%E6%B5%81%E6%95%B0%E6%8D%AE%E7%BB%9F%E8%AE%A1&sd=24-bit&sr=1536x864&vp=1536x802&je=0&ec=runtime&ea=version&el=v3.13.7&_u=CACAAEABEAAAACAAI~&jid=1411315286&gjid=1109798084&cid=426329494.1686413173&tid=UA-142226262-4&_gid=739023401.1693838405&_r=1&_slc=1&z=1778715342 的远程资源。（原因：CORS 请求未能成功）。

08:05:34.084 (info) [ObjectManager] fetched data "globalPatternMatrix" at 1693872334081 for server "CN" instrument.js:109:42
08:05:34.129 由于不符合规范，Cookie “_ga_4VJR7KRK8D”在未来会被视为“https://penguin-stats.cn/PenguinStats/api/v2/_private/result/pattern/CN/global/all”的跨网站 Cookie。 all
08:05:36.618 (info) [ObjectManager] fetched data "globalMatrix" at 1693872336618 for server "CN" instrument.js:109:42
08:05:36.627 由于不符合规范，Cookie “_ga_4VJR7KRK8D”在未来会被视为“https://penguin-stats.cn/PenguinStats/api/v2/_private/result/matrix/CN/global/all”的跨网站 Cookie。 all
08:05:37.156 (info) [ObjectManager] fetched data "zones" at 1693872337153 for server "CN" instrument.js:109:42
08:05:37.163 由于不符合规范，Cookie “_ga_4VJR7KRK8D”在未来会被视为“https://penguin-stats.cn/PenguinStats/api/v2/zones”的跨网站 Cookie。 zones
08:05:37.683 Storage: setItem failed:  DOMException: The quota has been exceeded. instrument.js:109:42
08:05:37.688 Storage: setItem failed:  DOMException: The quota has been exceeded. instrument.js:109:42
08:05:37.688 (info) [ObjectManager] fetched data "stages" at 1693872337688 for server "CN" instrument.js:109:42
08:05:37.692 由于不符合规范，Cookie “_ga_4VJR7KRK8D”在未来会被视为“https://penguin-stats.cn/PenguinStats/api/v2/stages?server=CN”的跨网站 Cookie。 stages
08:05:37.906 (info) [ObjectManager] fetched data "items" at 1693872337907 for server "CN" instrument.js:109:42
08:05:37.911 由于不符合规范，Cookie “_ga_4VJR7KRK8D”在未来会被视为“https://penguin-stats.cn/PenguinStats/api/v2/items”的跨网站 Cookie。 items
08:05:38.141 (info) [ObjectManager] fetched data "config" at 1693872338141 for server "CN" instrument.js:109:42
08:05:38.169 由于不符合规范，Cookie “_ga_4VJR7KRK8D”在未来会被视为“https://penguin-stats.cn/PenguinStats/api/v2/config”的跨网站 Cookie。 config
08:05:44.408 Glitter Drag: An external dragging behavior is detected content_script.js:686:17
08:05:46.115 (info) [Recognizer] initializing instrument.js:109:42
08:05:46.334 (info) [Recognizer] init: loading recognition backend from: /recognition/v4.5.1/penguin-recognizer.js instrument.js:109:42
08:05:46.389 (info) [Recognizer] init: recognition backend: js loaded instrument.js:109:42
08:05:47.095 (info) [Recognizer] init: recognition backend: wasm loaded instrument.js:109:42
08:05:47.171 (info) [Recognizer] init: preload icons: preloading instrument.js:109:42
08:05:48.077 (info) [Recognizer] init: preload icons: preloaded instrument.js:109:42
08:05:48.078 (info) [Recognizer] initialization completed with wasm version v4.6.0 instrument.js:109:42
08:05:48.130 (info) [Recognizer] start recognizing file Screenshot_IC-1.png with file content buffer 
ArrayBuffer { byteLength: 801926 }
instrument.js:109:42
08:05:48.450
(error) [Recognizer] caught wasm error 5932720 (bad any cast) responding with null result instrument.js:109:42
    y instrument.js:109
    value Console.js:95
    value Console.js:53
    t recognizer.js:220
    u recognition.bc48b4b7.js:1
    _invoke recognition.bc48b4b7.js:1
    m recognition.bc48b4b7.js:1
    L recognition.bc48b4b7.js:1
    o recognition.bc48b4b7.js:1
    (异步：promise callback)
    L recognition.bc48b4b7.js:1
    o recognition.bc48b4b7.js:1
    N recognition.bc48b4b7.js:1
    N recognition.bc48b4b7.js:1
    e recognition.bc48b4b7.js:1
    e RecognitionReport.vue:886
    f recognition.bc48b4b7.js:1
    _invoke recognition.bc48b4b7.js:1
    b recognition.bc48b4b7.js:1
    N recognition.bc48b4b7.js:1
    o recognition.bc48b4b7.js:1
    O recognition.bc48b4b7.js:1
    O recognition.bc48b4b7.js:1
    recognize RecognitionReport.vue:871
    e RecognitionReport.vue:911
    f recognition.bc48b4b7.js:1
    _invoke recognition.bc48b4b7.js:1
    b recognition.bc48b4b7.js:1
    N recognition.bc48b4b7.js:1
    o recognition.bc48b4b7.js:1
    (异步：promise callback)
    N recognition.bc48b4b7.js:1
    o recognition.bc48b4b7.js:1
    O recognition.bc48b4b7.js:1
    O recognition.bc48b4b7.js:1
    initAndRecognize RecognitionReport.vue:907
    VueJS 4
    click DynamicSizeBtn.vue:1
    VueJS 4
    click VBtn.ts:157
    VueJS 3
    i helpers.js:74
08:05:48.753 由于不符合规范，Cookie “_ga_4VJR7KRK8D”在未来会被视为“https://penguin-stats.cn/fonts/noto-serif-sc-700.81ba222e.woff2”的跨网站 Cookie。 noto-serif-sc-700.81ba222e.woff2
08:06:24.448 (info) [ThemeStyle] detecting theme style... instrument.js:109:42
```

相关截图：
![图片](https://github.com/penguin-statistics/recognizer/assets/81268244/0febd3bf-6cec-4394-80f5-5b3e33bc8e48)
![图片](https://github.com/penguin-statistics/recognizer/assets/81268244/b3856670-bafb-4901-b044-c7a64569b738)

结算页面截图原图：
![Screenshot_IC-1](https://github.com/penguin-statistics/recognizer/assets/81268244/7980f9d9-b7ff-4cfe-861b-35e3311e454b)

**Comment by Tinhone** [comment]
截图识别缺陷反馈 API 相关 issue：https://github.com/penguin-statistics/backend-next/issues/490
